spring:
  cloud:
    gateway:
      routes:
        - id: short-link-creator-user
          uri: lb://short-link-creator-user
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username

        - id: short-link-creator-link
          uri: lb://short-link-creator-link/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate