server:
  port: 8001

spring:
  application:
    name: short-link-creator-link
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-dev.yaml

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  domain:
    default: nurl.lnk:8001
  goto-domain:
    while-list:
      enable: true
      names: '哔哩哔哩,知乎,掘金,博客园'
      details:
        - bilibili.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml